#------------------------------------------------------------------
#     █████████  █████               ████   █████
#    ███░░░░░███░░███               ░░███  ░░███
#   ███     ░░░  ░███████    ██████  ░███  ███████    █████
#  ░███          ░███░░███  ███░░███ ░███ ░░░███░    ███░░
#  ░███    █████ ░███ ░███ ░███ ░███ ░███   ░███    ░░█████
#  ░░███  ░░███  ░███ ░███ ░███ ░███ ░███   ░███ ███ ░░░░███
#   ░░█████████  ████ █████░░██████  █████  ░░█████  ██████
#    ░░░░░░░░░  ░░░░ ░░░░░  ░░░░░░  ░░░░░    ░░░░░  ░░░░░░
#---------------------------------------------no_language_detection
#-- Typesetting
#------------------------------------------------------------------
format = """
[╭](bold fg:8)\
$username\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$time\
$line_break$character"""

right_format = """$battery"""
#------------------------------------------------------------------
#-- Option
#------------------------------------------------------------------
add_newline = true
command_timeout = 5000
#------------------------------------------------------------------
#-- Segment 
#------------------------------------------------------------------
[battery]
format = "[ $symbol$percentage ]($style)"
#------------------------------------------------------------------
[[battery.display]]
threshold = 50
style = "bold fg:14 bg:90"
#------------------------------------------------------------------
[username]
show_always = true
style_user = "bg:235"
style_root = "bg:53"
format = "[ $user ]($style)"
#------------------------------------------------------------------
[directory]
style = "bg:237"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
#------------------------------------------------------------------
[git_branch]
symbol = ""
style = "bg:60"
format = "[ $symbol $branch]($style)"
#------------------------------------------------------------------
[git_status]
style = "bg:60"
format = "[ $all_status$ahead_behind ]($style)"
#------------------------------------------------------------------
[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format = "[ 󰞌 $duration ]($style)"
style = "bold bg:62"
#------------------------------------------------------------------
[fill]
symbol = " "
style = "fg:8 bg:none"
#------------------------------------------------------------------
[time]
disabled = false
time_format = "%R"
style = "bg:62"
format = "[  $time ]($style)"
#------------------------------------------------------------------
[character]
disabled = false
format = """
[╰$symbol](fg:8) """
success_symbol = "[](bold fg:8)"
error_symbol = "[](bold fg:6)"
